Extended button added
step-up-labs/FloatingActionButton pull request #1
Opened 2016-09-21 10:24 UTC by JosefHruska

2016-09-21 11:11 UTC, JosefHruska commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +    }
Menu is automatically opened when it collapse from its expanded state.

2016-09-21 11:12 UTC, JosefHruska commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
>          mButtonSpacing = attr.getDimensionPixelSize(R.styleable.FloatingActionMenu_menu_buttonSpacing, mButtonSpacing);
Setters for menu text and default menu shape.

2016-09-21 11:13 UTC, JosefHruska commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +                                }
Menu should't open in extended state.

2016-09-21 11:19 UTC, JosefHruska commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +                }
Need to set icon position when animation already ended.

2016-09-21 11:21 UTC, TomWayne98 commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
>          init(context, attrs, defStyleAttr);
I use -1 constant to tell class that it current button will be extended. It called from "createExtendedButton" method in FloatingActionMenu class.

2016-09-21 12:14 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/CustomShape.java
> +    private float mButtonPadding = 64f;
Add paddings as xml dimensions. They can be easily overriden in landscape/tablets etc.

2016-09-21 12:14 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +    private float mLandscapePadding = 60f;
Add paddings as xml dimensions. They can be easily overriden in landscape/tablets etc.

2016-09-21 12:15 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +        if (defStyleAttr == -1){
Make the -1 as a named constant

2016-09-21 12:16 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +        mIsExtended = attr.getBoolean(R.styleable.FloatingActionButton_fab_isExtended, false);
Not formatted

2016-09-21 12:18 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +                //TODO add condition
Forgotten todo?

2016-09-21 12:18 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +                canvas.drawRoundRect(new RectF(0,0,Util.getScreenWidth(getContext()) -  Util.dpToPx(getContext(),mLandscapePadding),Util.dpToPx(getContext(),56f)),70f,70f, mErase);
Duplicated code, create a method

2016-09-21 12:20 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +        mMenuTextString = attr.getString(R.styleable.FloatingActionMenu_menu_menuText);
Better name it "FloatingActionMenu_menu_extendedButtonText"

2016-09-21 12:20 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +        mMenuTextColor = attr.getInt(R.styleable.FloatingActionMenu_menu_menuTextColor, Color.WHITE);
Rename to FloatingActionMenu_menu_extendedButtonTextColor

2016-09-21 12:24 UTC, davidvavra requested changes
Also please edit README.md - add section how to use extended FAB.

2016-09-21 15:22 UTC, JosefHruska commented on library/src/main/java/com/github/clans/fab/CustomShape.java
> +    private float mButtonPadding = 64f;
I realized that with last changes which I have made it's will use just one padding for both landscape and portrait thus I changed the name to mExtendedButtonPadding.

2016-09-21 17:30 UTC, davidvavra commented on library/src/main/res/values/dimens.xml
> +    <dimen name="custom_shape_buttonPadding">70dp</dimen>
Better name pls, custom shape would mean that user of the library can customize it. What is it exactly?

2016-09-21 17:31 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/CustomShape.java
>      private float mRadius = 75f;
Also please update README.md and add instructions how to use extended FAB.

2016-09-21 17:31 UTC, davidvavra requested changes

2016-09-22 09:08 UTC, davidvavra commented on README.md
> +        fab:menu_extendedButtonTextColor="Color.WHITE"
The value is really strange. Adding Java to XML? You mean @color/white?

2016-09-22 09:09 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +        if (defStyleAttr == -1){
This is still unnamed constant.

2016-09-22 09:09 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +       shapeDrawable = new CircleDrawable(new ExtendedButtonShadowShape(getContext()));
Wrong formatting

2016-09-22 09:10 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionButton.java
> +                    },300);
Wrong formatting

2016-09-22 09:11 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +    private String extendedButtonText = "Add new expense";
Hardcoding our text into the library? Replace with null value please.

2016-09-22 09:12 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +        mMenuText.setTextSize(16);
Make text size configurable as well, it's better to specify it in xml.

2016-09-22 09:13 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +            if(getChildAt(i) instanceof FloatingActionButton) {
Wrong formatting

2016-09-22 09:14 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +            if (mIsExtended) {
Wrong formatting

2016-09-22 09:14 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +            if (!mIsExtended) {
wrong formatting

2016-09-22 09:15 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +    public void setMenuText(String menuText) {
Rename to setExtendedButtonText

2016-09-22 09:15 UTC, davidvavra commented on library/src/main/java/com/github/clans/fab/FloatingActionMenu.java
> +    public void setMenuTextColor(int menuTextColor) {
Rename to setExtendedButtonTextColor

2016-09-22 09:16 UTC, davidvavra commented on library/src/main/res/anim/fab_replace_extended.xml
> +<?xml version="1.0" encoding="utf-8"?>
Rename to fab_extended_replace

2016-09-22 09:16 UTC, davidvavra commented on library/src/main/res/values/dimens.xml
> +    <dimen name="extend_button_shadow_padding">70dp</dimen>
Rename to extended_button_shadow_padding

2016-09-22 09:17 UTC, davidvavra commented on sample/src/main/res/anim/fab_replace_extended.xml
> +<?xml version="1.0" encoding="utf-8"?>
Why do we need this in the sample? It should be in the library imho.

2016-09-22 09:17 UTC, davidvavra requested changes

2016-09-22 13:39 UTC, merged